### ISSUE TITLE
Serilization of  secrets doesn't work 

### ISSUE THREAD

**Issue by rawoke083** [joshcarty/google-searchconsole#10]
HI
Great library!

I do have a problem, even specifying the serialize param: it keeps asking/opening the browser for the following up runs/calls

it does save it the file scc.json with the credentials but on re-run it just open the browser again.

```
import searchconsole
account = searchconsole.authenticate(client_config='client_secrets.json',serialize='scc.json')
webproperty = account['https://my-website/']
report = webproperty.query.range('today', days=-7).dimension('query').get()
print(report.rows)
```

Regards

**Comment by joshcarty** [comment]
Thanks Jacques!

Once you've created your credentials with `serialize`, you can pass them in with the `credentials` argument:

```python
 account = searchconsole.authenticate(client_config='client_secrets.json', credentials='scc.json')
```

I agree this could be clearer in the README. I'd gladly merge a pull request that makes this clearer - perhaps by providing an example?

**Comment by rawoke083** [comment]
Hi Thanks for response
I'm not sure when to specify serialize and when to specify credentials.
If the scc.json is not there(first run) the program exits/panics

`account = searchconsole.authenticate(client_config='client_secrets.json',serialize='scc.json',credentials='scc.json')`

**Comment by joshcarty** [comment]
No worries, so the idea is:

When you want to authenticate a new account you run:
```python
account = searchconsole.authenticate(client_config='client_secrets.json', serialize='scc.json')
```
Which will save your credentials to a file called `scc.json`.

From then on, you can just do:
```python
account = searchconsole.authenticate(client_config='client_secrets.json', credentials='scc.json')
```

**Comment by rawoke083** [comment]
Perfect thanks !
