### ISSUE TITLE
localhost refused to connect

### ISSUE THREAD

**Issue by pradyrk** [joshcarty/google-searchconsole#13]
I tried to use the search analytics script as guided in Readme, I have downloaded Oauth 2.0 "Other" type json from developer console and using the same. It prompts for a manual authentication in browser, when  I click on “Allow” to authenticate I am getting the  error "site cannot be reached, localhost refused to connect" . Do I need to set the redirect URL in the downloaded secrets or am I missing anything ? Please assist.

**Comment by joshcarty** [comment]
Hi pradyrk, apologies for the slow reply. Sounds like what your doing is right but could be related to your firewall or network settings. Have you tried to connect from a different network?

**Comment by pradyrk** [comment]
Sorry, it worked. We were trying initially in cloud based python Notebook IDE. I tried with local IDE, I was able to authenticate and pull data. However we moved to java based solution because of some business reasons. Thanks much!
