### ISSUE TITLE
Only 5000 rows when requesting day by day

### ISSUE THREAD

**Issue by diije** [joshcarty/google-searchconsole#15]
Hi,

Thanks for this lib which is very helpful.

However, when I'm trying to get data for one day only, I can't seem to get more than 5000 rows (despite the supposed 25000 rows limit).

Am I missing anything? Is there any way to navigate through queries pagination?

**Comment by joshcarty** [comment]
Hi Julien,

The package should paginate through all the results, with no upper limit. Are you able to get more than 5,000 rows if you request more than one day of data?

Would you share the request you're making?

**Comment by diije** [comment]
Hi,

Here's my request:

```
query = webproperty.query.range(start=start_date,stop=stop_date).dimension('query')
report = query.get()
print(len(report))
```

It seems I get more results when requesting on more than one day.

I also tried upgrading the lib (`pip install --upgrade git+https://github.com/joshcarty/google-searchconsole`) and I get `searchconsole-0.0.3` installed, is that the right version?

**Comment by joshcarty** [comment]
Your query looks good and you should have the most recent version. Is it possible that the site receives less than 5,000 different queries in a particular day?

**Comment by diije** [comment]
I tested this on several days, and several websites. All with more than 10,000 different queries per day for sure.
I also tested this on a brand new virtual env, and I still get only (and exactly) 5,000 rows.

Am I really the only one coming across this kind of limitation?

To be honest I'm starting to wonder if the number of rows I get for several days is reliable too.

**Comment by jceallonardo** [comment]
I think it's a bug with the GSC API itself. There's a similar problem in an R library I've used and I doubt that two different devs have the same bug for daily GSC data.

https://github.com/MarkEdmondson1234/searchConsoleR/issues/48

**Comment by andreamoro** [comment]
It's not a bug of the API rather than a feature (aka limit). 

@joshcarty you should consider implementing the startRow and rowLimit as per the API doc.
By having the startRow = startRow + 1 and rowLimit set to 5000 you should be able to iterate through the entire collection.

**Comment by joshcarty** [comment]
Hey @andreamoro, great to hear from you!

The package does paginate through the entire collection, like you say, by making multiple requests with the same query and incrementing the startRow (see [here](https://github.com/joshcarty/google-searchconsole/blob/master/searchconsole/query.py#L226)). 

This issue here seems to be that when you request only a single day's query data, you only get 5,000 rows despite the rowLimit being 25,000. I haven't been able to get to the bottom of why, but agree with @jceallonardo it's likely related to the underlying Google API as the R client library has the same issue.

**Comment by andreamoro** [comment]
Yes, saw later in the afternoon when I was playing around with the code. 
I also noticed the issue when digging with PostMan and direct calls to their API and as far as I can see even on multiple days, the 5K limits seems to exist?

**Comment by joshcarty** [comment]
Interesting. My understanding is that the default rowLimit is now 1,000 and can be increased up to 25,000. Besides what has been discussed here, I'm not sure where this isn't the case. Really keen to see some more queries that return 5,000 rows if you have some?

**Comment by andreamoro** [comment]
In theory the sites I'm working on right now should have more than 5000 queries per day. I will try to look to look at Analytics along this week.

**Comment by jasondavides** [comment]
Hello guys, 
I am late to the discussion, but I just found me in the same situation getting 5000 rows every time a request data.

Did you get to a new status of this situation?

**Comment by joshcarty** [comment]
Hey @jasondavides  - it's a weird one.

This package [requests 25,000 rows](https://github.com/joshcarty/google-searchconsole/blob/f9bc2a165ce88413087621a38552f7a2115965a4/searchconsole/query.py#L50) by default and keeps requesting 25,000 rows until it gets [nothing back](https://github.com/joshcarty/google-searchconsole/blob/f9bc2a165ce88413087621a38552f7a2115965a4/searchconsole/query.py#L326) or reaches a [limit you've explicitly set](https://github.com/joshcarty/google-searchconsole/blob/f9bc2a165ce88413087621a38552f7a2115965a4/searchconsole/query.py#L250).

If you've got the latest version of the package

```bash
$ pip3 install -u git+https://github.com/joshcarty/google-searchconsole
```
then there should be no reason for responses to be limited to 5,000 rows. Our best guess is that the underlying API is limiting the number of rows returned for certain queries.

Let me know if you come across a potential solution. It was mentioned above that [MarkEdmondson1234/searchConsoleR](https://github.com/MarkEdmondson1234/searchConsoleR) had a similar issue.

**Comment by jasondavides** [comment]
> Hey @jasondavides - it's a weird one.
> 
> This package [requests 25,000 rows](https://github.com/joshcarty/google-searchconsole/blob/f9bc2a165ce88413087621a38552f7a2115965a4/searchconsole/query.py#L50) by default and keeps requesting 25,000 rows until it gets [nothing back](https://github.com/joshcarty/google-searchconsole/blob/f9bc2a165ce88413087621a38552f7a2115965a4/searchconsole/query.py#L326) or reaches a [limit you've explicitly set](https://github.com/joshcarty/google-searchconsole/blob/f9bc2a165ce88413087621a38552f7a2115965a4/searchconsole/query.py#L250).
> 
> If you've got the latest version of the package
> 
> ```shell
> $ pip3 install -u git+https://github.com/joshcarty/google-searchconsole
> ```
> 
> then there should be no reason for responses to be limited to 5,000 rows. Our best guess is that the underlying API is limiting the number of rows returned for certain queries.
> 
> Let me know if you come across a potential solution. It was mentioned above that [MarkEdmondson1234/searchConsoleR](https://github.com/MarkEdmondson1234/searchConsoleR) had a similar issue.

Hey @joshcarty, I found that adding the parameter below kinda forces (I don't know how) the API to return more values, I can reach thousands more. BTW this happens when I try to get data for `query` dimension and `page`.

`
"dimensionFilterGroups": [
{
        "filters": [
            {
                "dimension": "device",
                "operator": "notEquals",
                "expression": "NotExistingDevice",
            }
        ]
    }
]
`

Please try adding that to the request body and let me know if that works for you.

**Comment by joshcarty** [comment]
@jasondavides that is interesting a filter like that will force more values. Good find!

I want to be pragmatic but I think it would be a mistake for the pacakge to do that by default in the request body. For now, if users are experiencing this issue, I'd encourage them to explicitly do something like:

```python
query.filter('device', 'NotExistingDevice', 'notEquals')
```

**Comment by jasondavides** [comment]
I agree with you! It's a good idea keeping it optional. Good luck with your tool and thanks for giving it to programmers. I'm not using it but if I need one this is going to be a good option.

Have a nice year and remember wash your hands 👍🏻👍🏻👍🏻

**Comment by scottdhjackson** [comment]
Hi guys,

Do you happen to know if it's possible to export queries that don't have any clicks but have impressions? /do you know if GSC stops returning data that has 0 clicks? 

We've managed to pull some queries with 0 clicks using filters, but when pulling the whole property it seems to cut off at 1.

Thanks in advance!

**Comment by joshcarty** [comment]
Hi @scottdhjackson - I would expect queries with any impressions to appear in the report even if they don't have clicks. I'm not certain though. It might be better to ask this in the [Discussions](https://github.com/joshcarty/google-searchconsole/discussions) than on this issue here.

**Comment by SMohsenM** [comment]
adding 'aggregationType':'byPage' to the query will fix the problem. source: https://support.google.com/webmasters/thread/162254466?hl=en&msgid=163239328

**Comment by seopowerbi** [comment]
> [@joshcarty](https://github.com/joshcarty) , it's interesting that the issue is still unresolved. The undocumented limitation with 5K rows per day is still there and I haven't managed to find anything on it apart from this discussion.
> 
> Have you discovered any other workarounds or explanations? It seems that the workaround with device filtering slightly changes the metric values 🤔

Same situation here; 2 years later; any news on that undocumented limitation ?
