### ISSUE TITLE
Example for filtering ?

### ISSUE THREAD

**Issue by GefenPuravida** [joshcarty/google-searchconsole#16]
Hi,
Thanks for this wonderful work, i find it super useful..
If only i could understand how to apply the different features like the "query.filter('query','dress','contains')" etc.

Any chance to see an example how the code should be ?

I'm trying this and other guesses but non of them filter the data...
![image](https://user-images.githubusercontent.com/48918701/58359693-6ca8c880-7e8d-11e9-8334-5e4e0bcca610.png)

I read the docs and the query.py (both this and the ga) over and over and wonder what i didn't understood.. no need to mention - i'm clueless in code!

**Comment by joshcarty** [comment]
Hey Gefen. Thanks, good to hear you find the package useful.

In your code above, you are calling `.get()` on your query before adding the filter. I think you want:

```python
import searchconsole
account = searchconsole.authenticate(client_config='client_secrets.json',
                                     credentials='credentials.json')
webproperty = account['https://www.example.com/']
query = (webproperty.query.range('today', days=-7)
                          .dimension('query')
                          .filter('query', 'example', 'contains'))
report = query.get()
df = report.to_dataframe()
print(df)
```

I've split the query across multiple lines to make it a bit more readable. Don't miss the outermost parentheses if you do.

Hope that all makes sense.

**Comment by GefenPuravida** [comment]
Wow, this is totally
A w e s o m e  ! ! !
