### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'query'

### ISSUE THREAD

**Issue by renekyewski** [joshcarty/google-searchconsole#19]
Hi Josh! Thanks for your package but I can't get it to work unfortunately. I get the following error for this line:
report = webproperty.query.range('today', days=-2).dimension('query').get()

AttributeError: 'NoneType' object has no attribute 'query'

Thanks for your help

**Comment by joshcarty** [comment]
Thanks! Double check the URL you have used to create your `webproperty` object. You need the correct `http(s)://` and to include any trailing slashes.

**Comment by matija2209** [comment]
Have the same problem no matter what I type in. Is this somehow connected to OAuth 2.0 credentials?

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'query'
```

**Comment by joshcarty** [comment]
Possibly, run `print(account.webproperties)` and check that the URL you are looking to query is in there.
