### ISSUE TITLE
Add support for dataState parameter

### ISSUE THREAD

**Issue by antoineeripret** [joshcarty/google-searchconsole#33]
Hi, 

First of all, thank you for the amazing work with this library. A huge time-saver! 

I wondered if support for the new (optional) parameter **dataState** (see https://developers.google.com/webmaster-tools/search-console-api-original/v3/searchanalytics/query) could be added to the query function.

It has been added in December in Google's documentation and If the value is equal to "all" (case-insensitive), data will include fresh data (vs only finalized data if the parameter is not specified). 

Thanks!

**Comment by joshcarty** [comment]
Thanks @antoineeripret - I didn't know about this!

Would you like to have a go at implementing it yourself? I'm happy to answer any questions and review your PR.

I think the implementation should be pretty simple. A good reference would be how `search_type` can be set [here](https://github.com/joshcarty/google-searchconsole/blob/master/searchconsole/query.py#L162).

**Comment by antoineeripret** [comment]
Great @joshcarty. 

I'll create it now. As you mentioned, the implementation should be simple so I may be able to do it :)

**Comment by joshcarty** [comment]
Solved in #34
