### ISSUE TITLE
Issue accessing discover/Google News data

### ISSUE THREAD

**Issue by nikotime** [joshcarty/google-searchconsole#50]
Hi there,

Thanks for the great package!

I'm trying to get Discover data as per your Search types code:

`report = webproperty.query.search_type('discover').range('today',days=-7).dimension('page').get().to_dataframe()`

However I get the error:
`TypeError: __new__() missing 1 required positional argument: 'position'`

Afraid I'm too new to Python to understand the error! Any tips?

I receive the same error from googleNews. The account I'm pulling from is for a news website with plenty of Discover and News traffic.

Thanks
Nick

**Comment by joshcarty** [comment]
Hey!

@antoineeripret and I added support for those new search types in the latest version. Try upgrading to the latest version with:

`$ pip install -U git+https://github.com/joshcarty/google-searchconsole`

Let me know if it works!

**Comment by nikotime** [comment]
Haha how silly of me! Can't believe I didn't upgrade the package. Thanks am
sure that will sort it

**Comment by nikotime** [comment]
Something seems to have gone a bit skewed with my Pip install , running upgrade doesn't seem to do anything so will try and clean things up and start again. Works beautifully on a fresh Google Colab. Thanks so much for upgrading to allow those elements so quickly after Google enabled them!
