### ISSUE TITLE
Add support for SearchType filter

### ISSUE THREAD

**Issue by july0426** [joshcarty/google-searchconsole#6]
我将授权的json保存在本地,但是还是会每次使用的时候需要通过浏览器来进行验证,该如何跳过浏览器呢

**Comment by joshcarty** [comment]
Hey!

I've been meaning to make this clearer in the documentation but hopefully [this comment should help](https://github.com/joshcarty/google-searchconsole/issues/1#issuecomment-356777553) you.

Let me know if you need further clarification.

**Comment by july0426** [comment]
谢谢你的回复,问题解决了.
但是我又有了新的问题,如果我想查找image类型的搜索,应该怎么传递参数
我尝试这样filter('searchType','image','contains'),但是报错了

![image](https://user-images.githubusercontent.com/33082765/42607023-53bc5e78-85b3-11e8-9aaa-4117e2f5702c.png)

**Comment by july0426** [comment]
好了,我搞定了.加了一段代码
@utils.immutable
    def searchType(self, *searchtype):
        """
        Return a new query that fetches the specified searchtype.
        Args:
            *searchtype (str): searchtype you would like to report on.
                Possible values: 'image','web','video'
                default  web
        Returns:
            `searchconsole.query.Query`
        Usage:
            >>> query.searchType('image')
            <searchconsole.query.Query(...)>
        """

        self.raw['searchType'] = list(searchtype)

        return self
建议加进去

**Comment by joshcarty** [comment]
Happy to add this feature! If you fork the repository, create a branch with this feature along with a simple test and make a pull request I'd love to merge this into the package.

I'd suggest `search_type` instead of `searchType` for the method name and passing a string instead `*args` but looks like a good start!

**Comment by joshcarty** [comment]
Feature added in 97afd2f. Thanks @july0426 for your contribution!
